version: '3.8'

services:
  redis:
    image: redis:8-alpine
    container_name: video-processing-redis
    ports:
      - '6379:6379'
    volumes:
      - ./.docker/redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
